# yaml-language-server: $schema=none
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  template:
    spec:
      containers:
      - name: plex
        env:
        - name: ADVERTISE_IP
          value: "http://99.113.188.114:32400/"