apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - deployment.yaml
  - service-qbit.yaml
  - ingress-qbit.yaml
  - service-sonarr.yaml
  - ingress-sonarr.yaml
  - service-radarr.yaml
  - ingress-radarr.yaml
  - service-lidarr.yaml
  - ingress-lidarr.yaml
  - service-prowlarr.yaml
  - ingress-prowlarr.yaml
  - service-flaresolverr.yaml
  - pf-sync-configmap.yaml
  - pvc.yaml
  - transfer_job.yaml

commonLabels:
  app.kubernetes.io/name: arr
  app.kubernetes.io/managed-by: argocd