apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbit-config-protected
  namespace: arr-stack
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn-protected
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun-protected
  namespace: arr-stack
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn-protected
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-protected
  namespace: arr-stack
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn-protected
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-protected
  namespace: arr-stack
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn-protected
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config-protected
  namespace: arr-stack
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn-protected
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-protected
  namespace: arr-stack
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn-protected
  resources:
    requests:
      storage: 2Gi