apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora
  namespace: collabora
spec:
  replicas: 1
  selector:
    matchLabels: { app: collabora }
  template:
    metadata:
      labels: { app: collabora }
    spec:
      nodeName: miniserver
      containers:
        - name: collabora
          image: collabora/code:latest
          imagePullPolicy: IfNotPresent
          env:
            # Allow WOPI requests from Nextcloud (regex, must escape dots)
            - name: domain
              value: "nextcloud\\.rcrumana\\.xyz"
            # TLS is terminated at Ingress; advertise server name for absolute URLs
            - name: extra_params
              value: "--o:ssl.enable=false --o:ssl.termination=true --o:server_name=collabora.rcrumana.xyz"
          ports:
            - name: http
              containerPort: 9980
          readinessProbe:
            tcpSocket: { port: 9980 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: 9980 }
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests: { cpu: 200m, memory: 1Gi }
            limits:   { cpu: "2",   memory: 3Gi }