apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-appdata-lh
  namespace: homarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi