apiVersion: v1
kind: ServiceAccount
metadata:
  name: homarr
  namespace: homarr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homarr-readonly
rules:
  - apiGroups: [""]
    resources: ["pods","services","nodes","namespaces","configmaps","secrets","persistentvolumeclaims"]
    verbs: ["get","list","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments","daemonsets","statefulsets","replicasets"]
    verbs: ["get","list","watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","list","watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods","nodes"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homarr-readonly-binding
subjects:
  - kind: ServiceAccount
    name: homarr
    namespace: homarr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homarr-readonly