apiVersion: batch/v1
kind: Job
metadata:
  name: transfer-orphan
  namespace: homarr
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      nodeName: miniserver
      restartPolicy: Never
      volumes:
      - name: dev
        hostPath: { path: /dev }
      - name: proc
        hostPath: { path: /proc }
      - name: replica
        hostPath: { path: /srv/longhorn/replicas/pvc-29d08798-c289-4578-8de0-8d311beb5530-4bae9c16 }  # orphan dir here
      - name: dest
        persistentVolumeClaim:
          claimName: nextcloud-appdata
      containers:

      # 1) Longhorn exporter (makes /host/dev/longhorn/<VOL>)
      - name: engine
        image: longhornio/longhorn-engine:v1.9.1
        securityContext: { privileged: true }
        volumeMounts:
        - { name: dev,     mountPath: /host/dev }
        - { name: proc,    mountPath: /host/proc }
        - { name: replica, mountPath: /volume }
        command: ["/bin/sh","-lc"]
        args:
          - |
            set -euo pipefail
            VOL=copy-replica
            SIZE=134217728      # from volume.meta
            # bind host /dev so the device appears under /host/dev/longhorn/<VOL>
            mount --rbind /host/dev /dev
            # Run exporter in foreground so this container stays alive
            launch-simple-longhorn "$VOL" "$SIZE"

      # 2) Copier (waits for device, mounts RO, rsyncs to PVC)
      - name: copy
        image: alpine:3.20
        securityContext: { privileged: true }   # needed for mount
        volumeMounts:
        - { name: dev,  mountPath: /host/dev }
        - { name: dest, mountPath: /dest }
        command: ["/bin/sh","-lc"]
        args:
          - |
            set -euo pipefail
            VOL=copy-replica
            DEV=/host/dev/longhorn/$VOL

            # Tools
            apk add --no-cache rsync util-linux e2fsprogs xfsprogs

            echo "Waiting for $DEV to become a *block device* with non-zero size…"
            for i in $(seq 1 120); do
              if [ -b "$DEV" ]; then
                SZ=$(blockdev --getsize64 "$DEV" 2>/dev/null || echo 0)
                if [ "${SZ:-0}" -gt 0 ]; then
                  echo "Device ready (size=${SZ} bytes)"; break
                fi
              fi
              [ $i -eq 120 ] && { echo "Timed out waiting for device"; exit 1; }
              sleep 2
            done

            mkdir -p /mnt/src
            echo "Attempting read-only mount…"
            ok=0
            for i in $(seq 1 10); do
              mount -o ro "$DEV" /mnt/src 2>/tmp/merr || \
              mount -t ext4 -o ro "$DEV" /mnt/src 2>>/tmp/merr || \
              mount -t xfs  -o ro "$DEV" /mnt/src 2>>/tmp/merr || true
              if mountpoint -q /mnt/src; then ok=1; break; fi
              echo "Mount attempt $i failed; retrying in 2s"; cat /tmp/merr || true; sleep 2
            done
            [ "$ok" = "1" ] || { echo "Mount failed after retries"; cat /tmp/merr || true; exit 1; }

            echo "Source filesystem:"
            df -hT /mnt/src || true
            echo "Destination filesystem:"
            df -hT /dest || true

            echo "Copying (rsync -aHAXS)…"
            rsync -aHAXS --info=progress2 /mnt/src/ /dest/
            echo "Copy complete"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: transfer-orphan-postgres
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      nodeName: miniserver
      restartPolicy: Never
      volumes:
      - name: dev
        hostPath: { path: /dev }
      - name: proc
        hostPath: { path: /proc }
      - name: replica
        hostPath: { path: /srv/longhorn/replicas/pvc-247097c3-04e7-40ed-95e4-56d3431aa9a6-d0c802ff }  # orphan dir here
      - name: dest
        persistentVolumeClaim:
          claimName: nextcloud-postgresql-data
      containers:

      # 1) Longhorn exporter (makes /host/dev/longhorn/<VOL>)
      - name: engine
        image: longhornio/longhorn-engine:v1.9.1
        securityContext: { privileged: true }
        volumeMounts:
        - { name: dev,     mountPath: /host/dev }
        - { name: proc,    mountPath: /host/proc }
        - { name: replica, mountPath: /volume }
        command: ["/bin/sh","-lc"]
        args:
          - |
            set -euo pipefail
            VOL=copy-replica-postgres
            SIZE=2147483648      # from volume.meta
            # bind host /dev so the device appears under /host/dev/longhorn/<VOL>
            mount --rbind /host/dev /dev
            # Run exporter in foreground so this container stays alive
            launch-simple-longhorn "$VOL" "$SIZE"

      # 2) Copier (waits for device, mounts RO, rsyncs to PVC)
      - name: copy
        image: alpine:3.20
        securityContext: { privileged: true }   # needed for mount
        volumeMounts:
        - { name: dev,  mountPath: /host/dev }
        - { name: dest, mountPath: /dest }
        command: ["/bin/sh","-lc"]
        args:
          - |
            set -euo pipefail
            VOL=copy-replica-postgres
            DEV=/host/dev/longhorn/$VOL

            # Tools
            apk add --no-cache rsync util-linux e2fsprogs xfsprogs

            echo "Waiting for $DEV to become a *block device* with non-zero size…"
            for i in $(seq 1 120); do
              if [ -b "$DEV" ]; then
                SZ=$(blockdev --getsize64 "$DEV" 2>/dev/null || echo 0)
                if [ "${SZ:-0}" -gt 0 ]; then
                  echo "Device ready (size=${SZ} bytes)"; break
                fi
              fi
              [ $i -eq 120 ] && { echo "Timed out waiting for device"; exit 1; }
              sleep 2
            done

            mkdir -p /mnt/src
            echo "Attempting read-only mount…"
            ok=0
            for i in $(seq 1 10); do
              mount -o ro "$DEV" /mnt/src 2>/tmp/merr || \
              mount -t ext4 -o ro "$DEV" /mnt/src 2>>/tmp/merr || \
              mount -t xfs  -o ro "$DEV" /mnt/src 2>>/tmp/merr || true
              if mountpoint -q /mnt/src; then ok=1; break; fi
              echo "Mount attempt $i failed; retrying in 2s"; cat /tmp/merr || true; sleep 2
            done
            [ "$ok" = "1" ] || { echo "Mount failed after retries"; cat /tmp/merr || true; exit 1; }

            echo "Source filesystem:"
            df -hT /mnt/src || true
            echo "Destination filesystem:"
            df -hT /dest || true

            echo "Copying (rsync -aHAXS)…"
            rsync -aHAXS --info=progress2 /mnt/src/ /dest/
            echo "Copy complete"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: transfer-orphan-redis
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      nodeName: miniserver
      restartPolicy: Never
      volumes:
      - name: dev
        hostPath: { path: /dev }
      - name: proc
        hostPath: { path: /proc }
      - name: replica
        hostPath: { path: /srv/longhorn/replicas/pvc-91e42e59-a276-421d-9fa6-5e94a07cf2ae-61d5e594 }  # orphan dir here
      - name: dest
        persistentVolumeClaim:
          claimName: nextcloud-redis-data
      containers:

      # 1) Longhorn exporter (makes /host/dev/longhorn/<VOL>)
      - name: engine
        image: longhornio/longhorn-engine:v1.9.1
        securityContext: { privileged: true }
        volumeMounts:
        - { name: dev,     mountPath: /host/dev }
        - { name: proc,    mountPath: /host/proc }
        - { name: replica, mountPath: /volume }
        command: ["/bin/sh","-lc"]
        args:
          - |
            set -euo pipefail
            VOL=copy-replica-redis
            SIZE=2147483648      # from volume.meta
            # bind host /dev so the device appears under /host/dev/longhorn/<VOL>
            mount --rbind /host/dev /dev
            # Run exporter in foreground so this container stays alive
            launch-simple-longhorn "$VOL" "$SIZE"

      # 2) Copier (waits for device, mounts RO, rsyncs to PVC)
      - name: copy
        image: alpine:3.20
        securityContext: { privileged: true }   # needed for mount
        volumeMounts:
        - { name: dev,  mountPath: /host/dev }
        - { name: dest, mountPath: /dest }
        command: ["/bin/sh","-lc"]
        args:
          - |
            set -euo pipefail
            VOL=copy-replica-redis
            DEV=/host/dev/longhorn/$VOL

            # Tools
            apk add --no-cache rsync util-linux e2fsprogs xfsprogs

            echo "Waiting for $DEV to become a *block device* with non-zero size…"
            for i in $(seq 1 120); do
              if [ -b "$DEV" ]; then
                SZ=$(blockdev --getsize64 "$DEV" 2>/dev/null || echo 0)
                if [ "${SZ:-0}" -gt 0 ]; then
                  echo "Device ready (size=${SZ} bytes)"; break
                fi
              fi
              [ $i -eq 120 ] && { echo "Timed out waiting for device"; exit 1; }
              sleep 2
            done

            mkdir -p /mnt/src
            echo "Attempting read-only mount…"
            ok=0
            for i in $(seq 1 10); do
              mount -o ro "$DEV" /mnt/src 2>/tmp/merr || \
              mount -t ext4 -o ro "$DEV" /mnt/src 2>>/tmp/merr || \
              mount -t xfs  -o ro "$DEV" /mnt/src 2>>/tmp/merr || true
              if mountpoint -q /mnt/src; then ok=1; break; fi
              echo "Mount attempt $i failed; retrying in 2s"; cat /tmp/merr || true; sleep 2
            done
            [ "$ok" = "1" ] || { echo "Mount failed after retries"; cat /tmp/merr || true; exit 1; }

            echo "Source filesystem:"
            df -hT /mnt/src || true
            echo "Destination filesystem:"
            df -hT /dest || true

            echo "Copying (rsync -aHAXS)…"
            rsync -aHAXS --info=progress2 /mnt/src/ /dest/
            echo "Copy complete"