apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: haproxy-public
  labels:
    app.kubernetes.io/name: haproxy-ingress
    app.kubernetes.io/component: ingress-class
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: haproxy-ingress.github.io/controller
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-public-config
  namespace: ingress-haproxy
  labels:
    app.kubernetes.io/name: haproxy-ingress
    app.kubernetes.io/component: ingress-class-config
data:
  # Security headers for all public services
  # These protect against common web vulnerabilities
  ssl-redirect: "true"