# platform/networking/haproxy-ingress/haproxy-debug-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ingress-config
  namespace: ingress-haproxy
data:
  # Log SNI information
  log-format: '"%ci:%cp [%t] %ft %b/%s %Tq/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r SNI:%[ssl_fc_sni]"'
  # Ensure proper SSL/TLS handling
  ssl-mode-async: "true"
  # Force SNI matching
  strict-sni: "false"  # Try false first to see if it helps