apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-public.yaml
  - restricted-internal.yaml

# Add common labels to all resources for easier management
commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: haproxy-ingress