apiVersion: batch/v1
kind: Job
metadata:
  name: vaultwarden-data-migration
  namespace: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden-data-migration
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: alpine:3.20
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-c"]
          args:
            - |
              set -e
              echo "Starting Vaultwarden data copy from hostPath to Longhorn PVC..."
              if [ -d /source ] && [ -n "$(ls -A /source 2>/dev/null || true)" ]; then
                mkdir -p /dest
                cp -a /source/. /dest/
                # Align ownership to container user/group (1000:1000)
                chown -R 1000:1000 /dest || true
                echo "Copy complete. Destination listing:"
                ls -la /dest || true
              else
                echo "Source appears empty; nothing to copy"
              fi
          volumeMounts:
            - name: source
              mountPath: /source
            - name: dest
              mountPath: /dest
      volumes:
        - name: source
          hostPath:
            path: /var/lib/vaultwarden
            type: DirectoryOrCreate
        - name: dest
          persistentVolumeClaim:
            claimName: vaultwarden-data