apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arr-lts2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rrumana/k8s-homelab
    targetRevision: main
    path: apps/base/arr-lts2
  destination:
    server: https://kubernetes.default.svc
    namespace: arr-lts2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true