apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/rrumana/k8s-homelab
    targetRevision: main
    path: apps/base/elasticsearch

  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true