apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rrumana/k8s-homelab
    targetRevision: main
    path: apps/base/homarr-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: homarr
  syncPolicy:
    # Manual by default to avoid clashing with existing Kustomize deployment.
    syncOptions:
      - CreateNamespace=true