apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr-backup
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rrumana/k8s-homelab
    targetRevision: main
    path: apps/ops/homarr-backup
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: homarr
  syncPolicy:
    # Manual sync so the backup Job only runs when you trigger it
    syncOptions:
      - CreateNamespace=true