apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Apply Longhorn prereqs (namespace/SA/backup-target) alongside the chart
    - repoURL: https://github.com/rrumana/k8s-homelab
      targetRevision: main
      path: platform/storage/longhorn/prereqs
      directory:
        recurse: true
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.9.1
      helm:
        valueFiles:
          - $values/platform/storage/longhorn/values.yaml
    - repoURL: https://github.com/rrumana/k8s-homelab
      targetRevision: main
      ref: values
    - repoURL: https://github.com/rrumana/k8s-homelab
      targetRevision: main
      path: platform/storage/longhorn/ingress
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true