apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: "6.2.1"
    chart: nextcloud
    helm:
      releaseName: nextcloud
      valueFiles:
        - https://raw.githubusercontent.com/rrumana/k8s-homelab/main/apps/base/nextcloud/values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/managed-by: argocd