apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    # Nuke mode: point exclusively at the minimal "nextcloud-nuke" kustomize
    # This will cause Argo to prune every object previously managed for Nextcloud (deployments, sts, services, PVCs, etc.)
    - repoURL: https://github.com/rrumana/k8s-homelab
      targetRevision: main
      path: apps/base/nextcloud-nuke
      kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # Ensure prunes delete dependent objects (foreground cascading)
      - PrunePropagationPolicy=foreground
      # Try to avoid order-related dangling, prune at the very end
      - PruneLast=true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/managed-by: argocd