
# platform/gitops/argocd/apps/rancher-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://releases.rancher.com/server-charts/stable
    targetRevision: "2.11.0"
    chart: rancher
    helm:
      releaseName: rancher
      valueFiles:
        - https://raw.githubusercontent.com/rrumana/k8s-homelab/main/platform/management/rancher/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true