apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/name: tempo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: "*"
      chart: tempo
      helm:
        releaseName: tempo
        valueFiles:
          - $values/platform/observability/tempo/values.yaml

    - repoURL: https://github.com/rrumana/k8s-homelab
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m