apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-local-1r
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict-local"   # keep the single replica on the same node as the pod
  fsType: "ext4"