apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ollama

resources:
  - storage-longhorn.yaml
  - ollama-deployment.yaml
  - webui-deployment.yaml
  - services.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: ollama
  app.kubernetes.io/managed-by: argocd