apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-to-rwx
  namespace: ollama
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: rsync
        image: alpine:3.20
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -euo pipefail
          apk add --no-cache rsync
          echo "Starting migration from /src to /dst"
          echo "Source contents:"
          ls -la /src/ || echo "Source directory is empty or doesn't exist"
          du -sh /src/ || echo "Cannot calculate size"
          echo "---"
          echo "Running rsync..."
          rsync -avHAX --progress --stats /src/ /dst/
          echo "---"
          echo "Destination contents after sync:"
          ls -la /dst/
          du -sh /dst/
          echo "Migration completed"
        volumeMounts:
        - { name: src, mountPath: /src }
        - { name: dst, mountPath: /dst }
      volumes:
      - name: src
        persistentVolumeClaim: { claimName: ollama-data-rwx }
      - name: dst
        persistentVolumeClaim: { claimName: ollama-data }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: webui-to-rwx
  namespace: ollama
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: rsync
        image: alpine:3.20
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -euo pipefail
          apk add --no-cache rsync
          echo "Starting migration from /src to /dst"
          echo "Source contents:"
          ls -la /src/ || echo "Source directory is empty or doesn't exist"
          du -sh /src/ || echo "Cannot calculate size"
          echo "---"
          echo "Running rsync..."
          rsync -avHAX --progress --stats /src/ /dst/
          echo "---"
          echo "Destination contents after sync:"
          ls -la /dst/
          du -sh /dst/
          echo "Migration completed"
        volumeMounts:
        - { name: src, mountPath: /src }
        - { name: dst, mountPath: /dst }
      volumes:
      - name: src
        persistentVolumeClaim: { claimName: open-webui-data-rwx }
      - name: dst
        persistentVolumeClaim: { claimName: open-webui-data }