apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app: ollama
    component: server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ollama
      component: server
  template:
    metadata:
      labels:
        app: ollama
        component: server
    spec:
      nodeName: miniserver
      #affinity:
      #  podAntiAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      - labelSelector:
      #          matchLabels:
      #            app: ollama
      #            component: server
      #        topologyKey: "kubernetes.io/hostname"
      containers:
      - name: ollama
        image: ollama/ollama:rocm
        ports:
        - containerPort: 11434
          name: http
        env:
        - name: OLLAMA_KEEP_ALIVE
          value: "5m"
        - name: HSA_OVERRIDE_GFX_VERSION
          value: "11.5.1"
        - name: OLLAMA_NUM_THREADS
          value: "12"
        - name: OLLAMA_NUM_GPU
          value: "999"
        - name: OLLAMA_FLASH_ATTENTION
          value: "1"
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        - name: dri
          mountPath: /dev/dri
        - name: kfd
          mountPath: /dev/kfd
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "48Gi"
            cpu: "24"
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data
      - name: dri
        hostPath:
          path: /dev/dri
          type: Directory
      - name: kfd
        hostPath:
          path: /dev/kfd
          type: CharDevice