---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data-lh
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data-lh
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  storageClassName: longhorn-protected
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  storageClassName: longhorn-protected
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 4Gi