apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  storageClassName: longhorn-protected
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 128Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  storageClassName: longhorn-protected
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-postgres
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  storageClassName: longhorn-protected
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 16Gi