apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  labels:
    app: ollama
    component: webui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ollama
      component: webui
  template:
    metadata:
      labels:
        app: ollama
        component: webui
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: ollama
                  component: webui
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama:11434"
        - name: DATABASE_URL
          value: "postgresql://openwebui:$(POSTGRES_PASSWORD)@postgres:5432/openwebui"
        - { name: POSTGRES_PASSWORD, valueFrom: { secretKeyRef: { name: openwebui-secrets, key: POSTGRES_PASSWORD } } }
        volumeMounts:
        - name: webui-files
          mountPath: /app/backend/data/uploads
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1"
      volumes:
      - name: webui-files
        persistentVolumeClaim:
          claimName: open-webui-data