# platform/management/rancher/backup-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rancher-backup
  namespace: cattle-system
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rancher-backup
            image: rancher/rancher-backup:v3.1.0
            command:
            - /bin/sh
            - -c
            - |
              kubectl create backup rancher-backup-$(date +%Y%m%d-%H%M%S) \
                --namespace cattle-resources-system
          restartPolicy: OnFailure
          serviceAccountName: rancher-backup