# platform/management/rancher/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cattle-system

resources:
  - namespace.yaml

generators:
  - helmChartInflationGenerator.yaml