apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-lh
  namespace: qdrant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi