apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-lh
  namespace: qdrant
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi