apiVersion: v1
kind: Service
metadata:
  name: qdrant
  labels:
    app: qdrant
  annotations:
    metallb.universe.tf/address-pool: default-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.223
  selector:
    app: qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
      protocol: TCP
    - name: grpc
      port: 6334
      targetPort: 6334
      protocol: TCP