# Longhorn configuration
defaultSettings:
  defaultReplicaCount: 1
  replicaAutoBalance: "disabled"
  autoSalvage: "false"
  concurrentReplicaRebuildPerNodeLimit: 0
  nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
  
  # Backup configuration (optional S3 endpoint)
  backupTarget: ""
  backupTargetCredentialSecret: ""
  
  # Performance settings
  guaranteedEngineManagerCPU: 0.1
  guaranteedReplicaManagerCPU: 0.1

  # Centralized data path on nodes
  defaultDataPath: /srv/longhorn

# UI configuration
ui:
  replicas: 2
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: longhorn-ui
              topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Storage class configuration
persistence:
  defaultClass: true
  defaultClassReplicaCount: 1
  reclaimPolicy: Delete

preUpgradeChecker:
  jobEnabled: false