apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elasticsearch
data:
  elasticsearch.yml: |-
    cluster.name: docker-cluster
    discovery.type: single-node
    xpack.security.enabled: false
    xpack.ml.enabled: false
    network.host: 0.0.0.0