apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
          imagePullPolicy: IfNotPresent
          env:
            # Single-node mode for simple homelab usage
            - name: discovery.type
              value: "single-node"
            # Disable security so Nextcloud can talk without credentials
            - name: xpack.security.enabled
              value: "false"
            # Reduce resource footprint by disabling ML
            - name: xpack.ml.enabled
              value: "false"
            # Heap sizing (adjust per your node)
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            # Listen on all interfaces inside cluster
            - name: network.host
              value: "0.0.0.0"
          ports:
            - name: http
              containerPort: 9200
            - name: transport
              containerPort: 9300
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "24"
              memory: "4Gi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: elasticsearch-data