apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elasticsearch
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - transfer.yaml

generatorOptions:
  disableNameSuffixHash: true