apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-lh
  namespace: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi