apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-8g
  namespace: elasticsearch
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
  namespace: elasticsearch
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn-protected
  resources:
    requests:
      storage: 8Gi