---
apiVersion: v1
kind: Pod
metadata:
  name: nextcloud-data-loader
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  # Optional: pin to the node that runs your workloads
  # nodeName: miniserver
  restartPolicy: Never
  containers:
    - name: loader
      image: alpine:3.20
      command: ["/bin/sh","-lc","sleep 36000"]
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumeMounts:
        - name: nc-data
          mountPath: /dest
  volumes:
    - name: nc-data
      persistentVolumeClaim:
        claimName: nextcloud-appdata-lh