# apps/base/nextcloud/values.yaml
# Chart: nextcloud/nextcloud (official community chart)

nextcloud:
  host: nextcloud.rcrumana.xyz
  trustedDomains:
    - nextcloud.rcrumana.xyz
  existingSecret:
    enabled: true
    secretName: nextcloud-admin
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password

  # Helpful when terminating TLS at HAProxy ingress
  phpClientHttpsFix:
    enabled: true
    protocol: https

  # Raise PHP/upload limits via php.ini fragments
  phpConfigs:
    zz-uploads.ini: |-
      upload_max_filesize=10G
      post_max_size=10G
      memory_limit=1024M
      max_execution_time=3600

  # Extra Nextcloud config merged as *.config.php
    99-overrides.config.php: |-
      <?php
      $CONFIG = [
        'overwriteprotocol' => 'https',
        'trusted_proxies' => ['10.0.0.0/8','172.16.0.0/12','192.168.0.0/16'],
      ];

# Single replica is recommended unless you add shared session/cache/file locking and appdata
replicaCount: 1
strategy:
  type: Recreate

image:
  repository: nextcloud

# --- Ingress (HAProxy) ---
ingress:
  enabled: true
  className: haproxy-public
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    haproxy-ingress.github.io/backend-protocol: "http"
    haproxy-ingress.github.io/timeout-client: "600s"
    haproxy-ingress.github.io/timeout-server: "600s"
  tls:
    - hosts: [nextcloud.rcrumana.xyz]
      secretName: nextcloud-tls

# --- App persistence (Nextcloud data) ---
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  existingClaim: nextcloud-appdata-lh

# Tighten IDs to match www-data
podSecurityContext:
  fsGroup: 33
  runAsUser: 33
  runAsGroup: 33
containerSecurityContext:
  runAsUser: 33
  runAsGroup: 33

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: "4"
    memory: 4Gi

# --- Cron for background jobs ---
cronjob:
  enabled: true
  schedule: "*/5 * * * *"

# --- PostgreSQL subchart (Bitnami) ---
postgresql:
  enabled: true
  auth:
    existingSecret: nextcloud-db
    username: nextcloud
    database: nextcloud
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
  primary:
    persistence:
      enabled: true
      existingClaim: nextcloud-postgresql-data-lh

# --- Redis subchart (Bitnami) for file locking/memcache ---
redis:
  enabled: true
  architecture: standalone
  auth:
    existingSecret: nextcloud-redis
    existingSecretPasswordKey: redis-password
  master:
    persistence:
      enabled: true
      existingClaim: nextcloud-redis-data-lh