# Ensure Longhorn has a default BackupTarget resource so PVC provisioning does not fail
# with: backuptarget.longhorn.io "default" not found
---
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backupTargetURL: ""
  credentialSecret: ""
  pollInterval: 300
  forceSync: false