apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-service-account
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/managed-by: argocd
  annotations:
    # Ensure SA exists before Helm chart hooks run
    argocd.argoproj.io/sync-wave: "-1"