apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: librechat
  labels: { app: llama, component: librechat }
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: librechat
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60