apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-db
  namespace: unifi
  labels:
    app: unifi-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: unifi-db
  template:
    metadata:
      labels:
        app: unifi-db
    spec:
      containers:
        - name: mongo
          image: mongo:6.0.11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: db-data
              mountPath: /data/db
            - name: init-mongo
              mountPath: /docker-entrypoint-initdb.d/init-mongo.js
              subPath: init-mongo.js
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: db-data
          hostPath:
            path: /home/rcrumana/Dev/docker/unifi/db/data
            type: DirectoryOrCreate
        - name: init-mongo
          hostPath:
            path: /home/rcrumana/Dev/docker/unifi/db/init-mongo.js
            type: File