---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-db-data
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi