apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: unifi
  labels:
    app: unifi
spec:
  type: ClusterIP
  selector:
    app: unifi
  ports:
    - name: https-ui
      port: 8443
      targetPort: 8443
      protocol: TCP