# platform/networking/haproxy-ingress/values.yaml
controller:
  configMap: haproxy-ingress-config
  
  # Your existing service configuration
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: default-pool
  
  config:
    ssl-redirect: "true"
    default-ssl-certificate: "ingress-haproxy/wildcard-default-cert-tls"
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  replicaCount: 1
  
  logs:
    enabled: true
    level: info  # Add this for better debugging

defaultBackend:
  enabled: false

serviceMonitor:
  enabled: true
  namespace: ingress-haproxy
  interval: 30s