controller:
  # Use LoadBalancer service type to get an external IP
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: default-pool
  
  # HAProxy configuration
  config:
    ssl-redirect: "true"
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    forwardfor: "add"
    timeout-server: "300s"
    timeout-connect: "30s"
    timeout-client: "300s"
    ssl-options: "no-sslv3 no-tlsv10 no-tlsv11"
    ssl-default-bind-ciphers: "ECDHE+AESGCM:ECDHE+AES256:ECDHE+AES128:!PSK:!DHE:!RSA:!DSS:!aNull:!MD5"
    check-interval: "2s"
  
  # Resource limits
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  replicaCount: 1
  
  logs:
    enabled: true

# Default backend
defaultBackend:
  enabled: false

# ServiceMonitor for Prometheus
serviceMonitor:
  enabled: true
  namespace: ingress-haproxy
  interval: 30s