# platform/networking/haproxy-ingress/values.yaml
controller:
  configMap: haproxy-ingress-config
  
  # Your existing service configuration
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: default-pool
  
  config:
    ssl-redirect: "true"
    default-ssl-certificate: "ingress-haproxy/cloudflare-origin-default-cert"
    ssl-options: "no-sslv3 no-tlsv10 no-tlsv11"
    ssl-ciphers: "ECDHE+AESGCM:ECDHE+AES256:ECDHE+AES128:!DHE:!RSA:!AES128:!RC4:!DES:!3DES:!MD5:!DSS"
    # Enable SNI debugging
    syslog-endpoint: "stdout"
    syslog-format: "raw"
    syslog-tag: "haproxy"
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  replicaCount: 1
  
  logs:
    enabled: true
    level: debug

defaultBackend:
  enabled: false

serviceMonitor:
  enabled: true
  namespace: ingress-haproxy
  interval: 30s