controller:
  # Use LoadBalancer service type to get an external IP
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: default-pool
  
  # HAProxy configuration
  config:
    ssl-redirect: "true"

  
  # Resource limits
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  replicaCount: 1
  
  logs:
    enabled: true

# Default backend
defaultBackend:
  enabled: false

# ServiceMonitor for Prometheus
serviceMonitor:
  enabled: true
  namespace: ingress-haproxy
  interval: 30s