apiVersion: batch/v1
kind: Job
metadata:
  name: seed-model-from-url
  namespace: llama
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: fetch
          image: curlimages/curl:8.10.1
          env:
            - name: MODEL_URL
              value: "https://huggingface.co/unsloth/gemma-3-4b-it-GGUF/resolve/main/gemma-3-4b-it-Q4_K_M.gguf?download=true"
          command: ["sh","-lc"]
          args:
            - |
              set -euo pipefail
              test -n "${MODEL_URL:-}" || { echo "MODEL_URL required"; exit 1; }
              cd /models
              echo "Downloading: ${MODEL_URL}"
              curl -L --fail "$MODEL_URL" -o model.gguf
              ln -sf model.gguf gemma-3-4b.gguf
          volumeMounts:
            - name: bus
              mountPath: /models
      volumes:
        - name: bus
          persistentVolumeClaim:
            claimName: llama-models-bus