# platform/networking/cilium/values.yaml
# Cilium v1.18+ compatible values for k3s, kube-proxy-free, same-L2 nodes

cluster:
  name: homelab
  id: 1

ipam:
  mode: kubernetes

# Use native/direct routing (no tunnels). 'tunnel' key is deprecated.
routingMode: native
# Scope direct routes to the cluster Pod CIDR
ipv4NativeRoutingCIDR: 10.42.0.0/16

endpointRoutes:
  enabled: true

# Kube-proxy is not present on this cluster, enable eBPF kube-proxy replacement explicitly
# (Some chart validations require explicit true/false)
kubeProxyReplacement: true

# Ensure kube-proxy-free features are active
hostServices:
  enabled: true
externalIPs:
  enabled: true
nodePort:
  enabled: true

# Disable Prometheus ServiceMonitors since Prometheus Operator CRDs are not installed
prometheus:
  enabled: false
  serviceMonitor:
    enabled: false

operator:
  replicas: 1
  prometheus:
    enabled: false
    serviceMonitor:
      enabled: false

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      className: haproxy-restricted
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - hubble.rcrumana.xyz
      tls:
        - secretName: hubble-ui-tls

# eBPF masquerading for egress
bpf:
  masquerade: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi