apiVersion: v1
kind: Service
metadata:
  name: homarr-redis
  labels:
    app: homarr-redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
  selector:
    app: homarr-redis
