homarr:
  # Keep single replica until DB cutover validated
  replicaCount: 0
  # RWO PVC -> Recreate on helm upgrades to avoid volume attach conflicts
  strategyType: Recreate

  image:
    repository: ghcr.io/homarr-labs/homarr
    pullPolicy: IfNotPresent
    tag: "v1.36.1"

  env:
    TZ: "America/Los_Angeles"
    REDIS_URL: "redis://homarr-helm-redis-master.homarr.svc.cluster.local:6379/0"

  # Keep encryption key in existing secret 'homarr-env'
  envSecrets:
    dbCredentials:
      existingSecret: "homarr-env"
      dbEncryptionKey: "SECRET_ENCRYPTION_KEY"

  # Built-in health endpoints (match current deployment)
  livenessProbe:
    httpGet:
      path: /api/health/live
      port: 7575

  readinessProbe:
    httpGet:
      path: /api/health/ready
      port: 7575

  # Container and Service ports
  containerPorts:
    http:
      port: 7575
      protocol: TCP

  service:
    enabled: true
    type: ClusterIP
    ports:
      app:
        port: 80
        targetPort: http
        protocol: TCP

  # Disable ingress for side-by-side bring-up (avoid host conflict).
  # We will enable at cutover and turn off the old ingress.
  ingress:
    enabled: true
    ingressClassName: haproxy-restricted
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: homarr.rcrumana.xyz
        paths:
          - path: /
    tls:
      - secretName: homarr-tls
        hosts:
          - homarr.rcrumana.xyz

  # Preserve current resources
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "50m"
      memory: 256Mi

  # Persist /appdata using the existing PVC
  persistence:
    homarrDatabase:
      enabled: true
      # Bind to the existing PV behind the homarr-appdata-protected PVC to avoid creating a new claim
      name: "homarr-database"
      volumeClaimName: ""
      storageClassName: "longhorn-protected"
      accessMode: "ReadWriteOnce"
      size: "1Gi"
      mountPath: "/appdata"

  # Keep initial scheduling behavior (nodeName: miniserver)
  # Map to nodeSelector by hostname to stay equivalent but schedulable.
  nodeSelector:
    kubernetes.io/hostname: miniserver

  rbac:
    enabled: false

  # Avoid resource name collisions with existing Kustomize deployment
  nameOverride: "homarr-helm"
  fullnameOverride: "homarr-helm"

  # External DB is configured via mysql dependency below (see root-level mysql: values)

  # Homarr chart DB flags
  database:
    externalDatabaseEnabled: false
    migrationEnabled: true

  additionalObjects:
    # One-shot, destructive rsync Job to migrate ALL content from the old PVC
    # to the new homarr-database PVC. This overwrites the destination and deletes
    # anything not present on the source, ensuring a 1:1 copy.
    - apiVersion: batch/v1
      kind: Job
      metadata:
        name: homarr-appdata-rsync
        annotations:
          # Ensure PVCs exist first; this runs after they bind.
          argocd.argoproj.io/sync-wave: "-1"
      spec:
        ttlSecondsAfterFinished: 86400
        backoffLimit: 0
        template:
          spec:
            restartPolicy: Never
            securityContext:
              fsGroup: 0
            containers:
              - name: rsync
                image: alpine:3.20
                imagePullPolicy: IfNotPresent
                securityContext:
                  runAsUser: 0
                  runAsGroup: 0
                command: ["/bin/sh","-lc"]
                args:
                  - |
                    set -eux
                    apk add --no-cache rsync
                    # Show what we're copying (first few entries)
                    echo "SOURCE LISTING (top 50):"
                    (find /src -maxdepth 3 -type f | sed -n '1,50p' || true)
                    # Perform a full, destructive, attribute-preserving sync
                    rsync -avHAX --numeric-ids --delete /src/ /dst/
                    # Show destination summary
                    echo "DEST LISTING (top 50):"
                    (find /dst -maxdepth 3 -type f | sed -n '1,50p' || true)
                volumeMounts:
                  - name: src
                    mountPath: /src
                    readOnly: true
                  - name: dst
                    mountPath: /dst
            volumes:
              - name: src
                persistentVolumeClaim:
                  claimName: homarr-appdata-protected
              - name: dst
                persistentVolumeClaim:
                  claimName: homarr-database

# Database subchart: Bitnami MySQL (replication)
mysql:
  architecture: replication
  auth:
    existingSecret: "homarr-mysql-secret"
    username: "homarr"
    database: "homarrdb"
  primary:
    persistence:
      enabled: true
      storageClass: "longhorn-protected"
      size: 2Gi
  secondary:
    replicaCount: 1
    persistence:
      enabled: true
      storageClass: "longhorn-protected"
      size: 2Gi

# Session store subchart: Bitnami Redis (replication)
redis:
  architecture: replication
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      storageClass: "longhorn-protected"
      size: 1Gi
  replica:
    replicaCount: 1
    persistence:
      enabled: true
      storageClass: "longhorn-protected"
      size: 1Gi