homarr:
  ingress:
    enabled: true
    ingressClassName: haproxy-restricted
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: homarr.rcrumana.xyz
        paths:
          - path: /
    tls:
      - secretName: homarr-tls
        hosts:
          - homarr.rcrumana.xyz

  service:
    enabled: true
    type: ClusterIP
    ports:
      app:
        port: 80
        targetPort: http
        protocol: TCP