apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-pf-sync
data:
  pf-sync.sh: |
    #!/bin/sh
    set -eu

    PF_FILE="${PF_FILE:-/pf/state/forwarded_port}"
    WEBUI_PORT="${QB_WEBUI_PORT:?missing QB_WEBUI_PORT}"
    echo "pf-sync(sidecar): watching $PF_FILE for qB WebUI :$WEBUI_PORT"

    last=""
    while true; do
      if [ -f "$PF_FILE" ]; then
        p="$(cat "$PF_FILE" 2>/dev/null || true)"
        case "$p" in
          ''|*[!0-9]*) : ;; # not a number yet
          *)
            if [ "$p" != "$last" ]; then
              echo "pf-sync(sidecar): new forwarded port $p -> applying to qB"
              # Login (cookie jar at /tmp/c)
              if ! curl -fsS -c /tmp/c -b /tmp/c \
                   --data "username=${QB_USERNAME}&password=${QB_PASSWORD}" \
                   "http://127.0.0.1:${WEBUI_PORT}/api/v2/auth/login" >/dev/null; then
                echo "pf-sync(sidecar): login failed"
              else
                # Set listen_port (encode JSON as form field 'json')
                if curl -fsS -b /tmp/c \
                     --data-urlencode "json={\"listen_port\": ${p}}" \
                     "http://127.0.0.1:${WEBUI_PORT}/api/v2/app/setPreferences" >/dev/null; then
                  echo "pf-sync(sidecar): set listen_port=${p} OK"
                  last="$p"
                else
                  echo "pf-sync(sidecar): setPreferences failed"
                fi
              fi
            fi
            ;;
        esac
      fi
      sleep 5
    done
