apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "nfs://192.168.1.10:/mnt/Cold/Longhorn_Backups"
  credentialSecret: ""         # NFS usually doesn't need a secret
  pollInterval: 5m0s 