apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  storageClassName: longhorn-protected
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 64Gi
