apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  labels:
    app: jellyfin
  annotations:
    metallb.universe.tf/address-pool: default-pool
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.225
  selector:
    app: jellyfin
  ports:
  - name: web
    port: 8096
    targetPort: 8096
    protocol: TCP