apiVersion: apps/v1
kind: Deployment
metadata:
  name: arr-lts2
  labels: { app: arr-lts2 }
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels: { app: arr-lts2 }
  template:
    metadata:
      labels: { app: arr-lts2 }
    spec:
      volumes:
        - name: dev-net-tun
          hostPath: { path: /dev/net/tun, type: CharDevice }
        - name: gluetun
          hostPath: { path: /home/rcrumana/Dev/docker/gluetun_lts2, type: DirectoryOrCreate }
        - name: qbit-config
          hostPath: { path: /home/rcrumana/Dev/docker/qbittorrent_lts2, type: DirectoryOrCreate }
        - name: media
          hostPath: { path: /media, type: Directory }
        - name: downloads
          hostPath: { path: /media/Torrent/Downloads, type: Directory }
        - name: movies
          hostPath: { path: /media/Torrent/Movies, type: Directory }
        - name: shows
          hostPath: { path: /media/Torrent/Shows, type: Directory }
        - name: pf-state
          emptyDir: {}
        - name: pf-sync
          configMap:
            name: gluetun-pf-sync
            defaultMode: 0755
      containers:
        - name: gluetun
          image: qmcgaw/gluetun:latest
          securityContext:
            privileged: true
            capabilities: { add: ["NET_ADMIN"] }
          envFrom:
            - secretRef: { name: gluetun-env }
          env:
            - { name: FIREWALL_INPUT_PORTS, value: "8022" }
            - { name: HEALTH_TARGET_ADDRESS, value: "127.0.0.1:9999" }
            - { name: QB_WEBUI_PORT, value: "8022" }
            - { name: VPN_PORT_FORWARDING_STATUS_FILE, value: "/pf/state/forwarded_port" }
          volumeMounts:
            - { name: dev-net-tun, mountPath: /dev/net/tun }
            - { name: gluetun,     mountPath: /gluetun }
            - { name: pf-state, mountPath: /pf/state }
          resources:
            requests: { cpu: "200m", memory: "256Mi" }
            limits:   { cpu: "24", memory: "2Gi" }

        - name: pf-sync
          image: curlimages/curl:8.7.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-c","/scripts/pf-sync.sh"]
          env:
            - { name: PF_FILE, value: "/pf/state/forwarded_port" }
            - { name: QB_WEBUI_PORT, value: "8022" }
            - { name: QB_USERNAME, valueFrom: { secretKeyRef: { name: qb-webui-creds, key: username } } }
            - { name: QB_PASSWORD, valueFrom: { secretKeyRef: { name: qb-webui-creds, key: password } } }
          volumeMounts:
            - { name: pf-sync, mountPath: /scripts/pf-sync.sh, subPath: pf-sync.sh }
            - { name: pf-state, mountPath: /pf/state }
          resources:
            requests: { cpu: "5m", memory: "16Mi" }
            limits:   { cpu: "25m", memory: "64Mi" }  

        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent
          env:
            - { name: PUID, value: "1000" }
            - { name: PGID, value: "1000" }
            - { name: TZ,   value: "America/Los_Angeles" }
            - { name: WEBUI_PORT, value: "8022" }
            - { name: TORRENTING_PORT, value: "6883" }
            - { name: DOCKER_MODS, value: "ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest" }
          ports:
            - { name: webui, containerPort: 8022, protocol: TCP }
          volumeMounts:
            - { name: qbit-config, mountPath: /config }
            - { name: downloads,   mountPath: /downloads }
            - { name: movies,      mountPath: /movies }
            - { name: shows,       mountPath: /shows }
            - { name: media,       mountPath: /media }
          resources:
            requests: { cpu: "200m", memory: "256Mi" }
            limits:   { cpu: "24", memory: "2Gi" }  