apiVersion: v1
kind: Service
metadata:
  name: portfolio-https
  namespace: dev
  annotations:
    haproxy-ingress.github.io/secure-backends: "true"
    haproxy-ingress.github.io/backend-protocol: "h1-ssl"
spec:
  ports:
    - name: https
      port: 4321
      targetPort: 4321
  type: ClusterIP