# Tempo (single-binary) values for homelab
# Namespace will be managed by Argo CD Application (CreateNamespace=true)

tempo:
  # Provide a minimal valid config for Tempo single-binary
  # This schema matches the grafana/tempo chart expectations
  config: |
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        otlp:
          protocols:
            http:
            grpc:
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
    compactor:
      compaction:
        block_retention: 168h
    metrics_generator:
      enabled: false

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 20Gi

# Resources suitable for a small homelab
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi

# Service for in-cluster access (Grafana datasource)
service:
  type: ClusterIP
  port: 3200

# Enable ServiceMonitor for Prometheus scraping
serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack

# Keep the Helm chart-level flag disabled to avoid the separate metrics generator deployment
metricsGenerator:
  enabled: false
  additionalLabels:
    release: kube-prometheus-stack

# Ensure PVC write permissions for Tempo (statefulset runs as non-root by default)
podSecurityContext:
  fsGroup: 10001
  fsGroupChangePolicy: OnRootMismatch

securityContext:
  runAsUser: 10001
  runAsGroup: 10001
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL