apiVersion: batch/v1
kind: Job
metadata:
  name: fix-immich-postgres-perms
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: fix-perms
        image: alpine:3.20
        command:
          - /bin/sh
          - -c
          - |
            set -eux

            echo "===== USER INFO ====="
            id

            echo "===== CHECK PATHS EXIST ====="
            ls -ld /var || true
            ls -ld /var/lib || true
            ls -ld /var/lib/postgresql || true
            ls -ld /var/lib/postgresql/data || true

            echo "===== STAT BEFORE ====="
            stat -c '%a %U:%G %n' /var/lib/postgresql || true
            stat -c '%a %U:%G %n' /var/lib/postgresql/data || true

            echo "===== LIST TOP-LEVEL OF DATA DIR (BEFORE) ====="
            ls -la /var/lib/postgresql/data || true

            echo "===== ATTEMPT CHOWN ====="
            chown -R 999:999 /var/lib/postgresql/data || {
              echo "chown failed with exit code $?"; exit 1;
            }

            echo "===== ATTEMPT CHMOD ON DATA DIR ====="
            chmod 700 /var/lib/postgresql/data || {
              echo "chmod failed with exit code $?"; exit 1;
            }

            echo "===== STAT AFTER ====="
            stat -c '%a %U:%G %n' /var/lib/postgresql || true
            stat -c '%a %U:%G %n' /var/lib/postgresql/data || true

            echo "===== SAMPLE OF PERMS INSIDE (AFTER) ====="
            find /var/lib/postgresql/data -maxdepth 3 -printf '%m %U:%G %p\n' | head -n 50 || true

            echo "===== DONE, EXITING SUCCESSFULLY ====="
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: immich-postgres-data
