apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-data
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
spec:
  storageClassName: longhorn-protected
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
spec:
  storageClassName: longhorn-protected
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi