apiVersion: batch/v1
kind: Job
metadata:
  name: recopy-immich-postgres-from-nfs
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: recopy
        image: alpine:3.20
        command:
          - /bin/sh
          - -c
          - |
            set -eux

            echo "===== WHO AM I ====="
            id

            echo "===== BEFORE WIPE ====="
            df -h /new || true
            du -sh /new || true
            ls -la /new || true

            echo "===== WIPING PVC CONTENT (KEEPING MOUNTPOINT) ====="
            # Remove everything under /new, but not /new itself
            find /new -mindepth 1 -maxdepth 1 -exec rm -rf {} +
            echo "===== AFTER WIPE ====="
            du -sh /new || true
            ls -la /new || true

            echo "===== SOURCE (NFS) TOP LEVEL ====="
            ls -la /old || true

            echo "===== COPYING /old -> /new (cp -a) ====="
            cp -a /old/. /new/.

            echo "===== FIXING OWNERSHIP AND PERMISSIONS ====="
            # Make sure everything belongs to the postgres UID/GID
            chown -R 999:999 /new
            # PG needs the data dir itself locked down
            chmod 700 /new
            # (Optionally tighten everything else)
            find /new -type d -exec chmod 700 {} \; || true
            find /new -type f -exec chmod 600 {} \; || true

            echo "===== VERIFY KEY FILES ====="
            stat -c '%s bytes %a perms %U:%G %n' /new/base/16384/pg_filenode.map || true
            echo "---- hexdump (PVC, first 64 bytes) ----"
            hexdump -C /new/base/16384/pg_filenode.map | head || true

            echo "===== DONE SUCCESSFULLY ====="
        volumeMounts:
        - name: new
          mountPath: /new
        - name: old
          mountPath: /old
      volumes:
      - name: new
        persistentVolumeClaim:
          claimName: immich-postgres-data
      - name: old
        hostPath:
          path: /NAS/Cloud/Immich/postgres   # <-- change here if your original dir was renamed
          type: Directory
