apiVersion: batch/v1
kind: Job
metadata:
  name: recopy-immich-ml-cache-from-nfs
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: recopy-ml-cache
        image: alpine:3.20
        command:
          - /bin/sh
          - -c
          - |
            set -eux

            echo "===== WHO AM I ====="
            id

            echo "===== PVC (/new) BEFORE WIPE ====="
            df -h /new || true
            du -sh /new || true
            ls -la /new || true

            echo "===== WIPING PVC CONTENT (KEEPING MOUNTPOINT) ====="
            # Remove everything under /new, but not /new itself
            find /new -mindepth 1 -maxdepth 1 -exec rm -rf {} +
            echo "===== PVC AFTER WIPE ====="
            du -sh /new || true
            ls -la /new || true

            echo "===== SOURCE (NFS, /old) TOP LEVEL ====="
            ls -la /old || true

            echo "===== COPYING /old -> /new (cp -a) ====="
            cp -a /old/. /new/.

            echo "===== FIXING OWNERSHIP AND PERMISSIONS ====="
            # ML container runs as root by default, but we can keep it neat
            chown -R 0:0 /new
            find /new -type d -exec chmod 755 {} \; || true
            find /new -type f -exec chmod 644 {} \; || true

            echo "===== SAMPLE OF CONTENTS (PVC) ====="
            find /new -maxdepth 3 -type f | head -n 50 || true

            echo "===== DONE SUCCESSFULLY ====="
        volumeMounts:
        - name: new
          mountPath: /new
        - name: old
          mountPath: /old
      volumes:
      - name: new
        persistentVolumeClaim:
          claimName: immich-ml-cache
      - name: old
        hostPath:
          path: /NAS/Cloud/Immich/model-cache   # <-- change if needed
          type: Directory
