apiVersion: v1
kind: Pod
metadata:
  name: copy-immich-ml-cache
spec:
  restartPolicy: Never
  containers:
  - name: copy
    image: alpine:3.20
    command:
      - /bin/sh
      - -c
      - |
        set -e
        echo "Copying ML cache from /old to /new..."
        cp -a /old/. /new/.
        echo "Done."
    volumeMounts:
      - name: old
        mountPath: /old
      - name: new
        mountPath: /new
  volumes:
    - name: old
      hostPath:
        path: /NAS/Cloud/Immich/model-cache
        type: Directory
    - name: new
      persistentVolumeClaim:
        claimName: immich-ml-cache