apiVersion: v1
kind: Pod
metadata:
  name: copy-immich-postgres
spec:
  restartPolicy: Never
  containers:
  - name: rsync
    image: alpine:3.20
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache rsync \
        && rsync -aHAXv --delete /old/ /new/ \
        && chown -R 999:999 /new
    volumeMounts:
      - name: old
        mountPath: /old
      - name: new
        mountPath: /new
  volumes:
    - name: old
      hostPath:
        path: /NAS/Cloud/Immich/postgres
        type: Directory
    - name: new
      persistentVolumeClaim:
        claimName: immich-postgres-data
