apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      nodeName: miniserver
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: plex
        image: lscr.io/linuxserver/plex:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        - name: VERSION
          value: "latest"
        - name: ADVERTISE_IP
          value: "http://99.113.188.114:32400/"
        ports:
        - name: web
          containerPort: 32400
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: tv
          mountPath: /tv
        - name: movies
          mountPath: /movies
        - name: music
          mountPath: /music
        - name: dri
          mountPath: /dev/dri
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "8Gi"
            cpu: "24"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-config
      - name: tv
        hostPath:
          path: /NAS/Torrent/Shows
          type: Directory
      - name: movies
        hostPath:
          path: /NAS/Torrent/Movies
          type: Directory
      - name: music
        hostPath:
          path: /NAS/Torrent/Music
          type: Directory
      - name: dri
        hostPath:
          path: /dev/dri
          type: Directory