apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - migration.yaml

commonLabels:
  app.kubernetes.io/name: plex
  app.kubernetes.io/managed-by: argocd