---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-lh
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 32Gi